export const PRODUCT_METADATA_TIMEOUT_MS = 5000;
export const PRODUCT_METADATA_STRATEGY_TIMEOUT_MS = 1800;
export const PRODUCT_METADATA_REDIRECT_TIMEOUT_MS = 1800;
export const PRODUCT_METADATA_MAX_REDIRECTS = 4;
export const PRODUCT_METADATA_MAX_HTML_BYTES = 1_000_000;
export const PRODUCT_METADATA_CACHE_TTL_MS = 5 * 60 * 1000;
